---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - include_tasks: tasks/ansible-setup.yml
    - include_tasks: tasks/dotfiles.yml

    - name: install packages
      package:
        name:
          - tmux
        state: latest

    - name: Ensure configured homebrew packages are installed.
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: present
      loop: "{{ homebrew_installed_packages }}"
      notify:
        - Clear homebrew cache
